server.port=8080

# Application Name
spring.application.name=type-b-be

# Logging Configuration
logging.level.root=INFO
logging.level.com.typeb=DEBUG

# Jackson Configuration (JSON)
spring.jackson.serialization.indent-output=true
